API_ID = int(input("API_ID: "))
API_HASH = input("API_HASH ")
BOT_TOKEN = input("BOT_TOKEN: ")
SESSION_NAME = input("SESSION_NAME: ")
COMMAND_PREFIXES = input("COMMAND_PREFIXES: ")
BOTLOG_CHATID = input("BOTLOG_CHATID: ")
DATABASE_URL = input("DATABASE_URL: ")
SUDO_USERS = list(map(int, input("SUDO_USERS: ").split()))
